### ISSUE TITLE
BSB LAN Adapter 

### ISSUE THREAD

**Issue by FreeKillerLP** [1coderookie/BSB-LPB-LAN#13]
Woher bekomme ich diese Blaue Platine?
ich möchte sie kaufen

**Comment by Schaefchen89** [comment]
Bausätze erhältlich!
Auf Anfrage sind Platinen mit entsprechenden Bauteilen für die Verwendung am Arduino Due oder ESP32 erhältlich, bei Interesse bitte Frederik eine e-Mail an bsb (ät) code-it.de schicken (Deutsch/Englisch).
