### ISSUE TITLE
Unverständlicher Satz in Kap. 10.1.1

### ISSUE THREAD

**Issue by DE-cr** [1coderookie/BSB-LPB-LAN#8]
"Sollte dein Regler einen BSB- und einen LPB-Anschluss aufweisen und kein weiterer Regler via LPB (bspw. eines weiteren Wärmeerzeugers bei einer Kaskadenschaltung, ein Solaranlagenregler o.ä.) und möchtest du nur Zugriff auf diesen einen Regler, [...]"

Fehlt hier ein "angeschlossen sein" oder ähnliches vor der öffnenden Klammer?

**Comment by 1coderookie** [comment]
Exakt :) 
Danke!
