### ISSUE TITLE
/JB nicht dokumentiert

### ISSUE THREAD

**Issue by DE-cr** [1coderookie/BSB-LPB-LAN#9]
Beschreibung des URL-Kommandos /JB fehlt in Kapitel 5

**Comment by 1coderookie** [comment]
Stimmt, danke für den Hinweis - es kann auch sein, dass da noch andere fehlen, weil dann die interaktive Swagger-JSON-Doku kam und ich mich nicht weiter um die JSON-Doku gekümmert habe.. Das werde ich bei Gelegenheit nochmal checken und vor einem Hinzufügen dann mit dem Autor der interaktiven Doku Rücksprache halten, da ich persönlich von JSON und den Befehlen nicht wirklich Ahnung habe.. :( ;)
